name: Build FoxOS Base Images

on:
  workflow_dispatch: {}

jobs:
  build-base-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install virtualization tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system virtinst

      - name: Make build scripts executable
        run: |
          chmod +x scripts/build-foxos-base-x86_64.sh

      - name: Build FoxOS base image (x86_64)
        run: |
          scripts/build-foxos-base-x86_64.sh

      - name: Upload qcow2 artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: FoxOS-Base-x86_64
          path: output/FoxOS-Base-x86_64.qcow2
